global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "Spark Executors Metrics"
    metrics_path: "/metrics/executors/prometheus"
    scrape_interval: 15s
    static_configs:
      - targets: ["spark:4040"]

  - job_name: "All Spark Metrics"
    metrics_path: "/metrics/prometheus"
    scrape_interval: 15s
    static_configs:
      - targets: ["spark:4040"]
