name: CI

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Linting with flake8
      run: |
        pip install flake8
        flake8 ./pyspark_app

    - name: Update Docker Compose
      run: sudo apt-get -y install --only-upgrade docker-compose

    - name: Build the Docker Compose
      run: |
        docker-compose build
