name: CI

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Linting with flake8
      run: |
        pip install flake8
        flake8 ./pyspark_app

    # By default the GitHub Actions Ubuntu agents have Docker Compose 1.x installed
    - name: Install Latest Docker Compose
      run: |
        VERSION=$(curl --silent https://api.github.com/repos/docker/compose/releases/latest | jq --raw-output .name -r)
        curl -L https://github.com/docker/compose/releases/download/${VERSION}/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    # Smoke Test has to be disabled in CI due to this issue
    # https://stackoverflow.com/questions/72061272/docker-compose-volume-mount-issue-in-github-actions-checked-out-repository
    - name: Run Smoke Test
      run: ./smoke-test.sh
      shell: bash
