name: CI

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Linting with flake8
      run: |
        pip install flake8
        flake8 ./pyspark_app

    - name: Install Latest Docker Compose
      run: |
        VERSION=$(curl --silent https://api.github.com/repos/docker/compose/releases/latest | jq --raw-output .name -r)
        curl -L https://github.com/docker/compose/releases/download/${VERSION}/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose

    - name: Build the Docker Compose
      run: |
        docker-compose build
